name : Build Job
on:
  push:
    branches:
      - main
jobs:
  bazelBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - run : cd bazel-ops && bazelisk build //calculator/...
      - run : bazelisk test //calculator/...
