# name: First workflow
# on:
#   push:
#     branches: 
#       - main

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello from Job 1"
#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello
#         run: echo "Hello from Job 4"


name: "Task : Security check and Environment verification"
on : [push]
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : Security Check
        run: | 
          if [ "${{secrets.PASSWORD}}" == "" ]; then
            echo "Critical : Password not set"
            exit 1

          else echo "Security Check Passed"
          fi
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform version check
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
      - name: Check Terraform version
        run: terraform version
