name: First workflow
on:
  push:
    branches: 
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from Job 1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from Job 2"
