name : Terraform template
on : 
  workflow_call:
    secrets:
      api_key:
        required: true
    inputs:
      environment:
        required: true
        type: string
jobs:
  terraform:
    runs-on: ubuntu-latest
    name : "Run Terraform ${{ inputs.environment }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: "Terraform Init"
        run: terraform version
        working-directory: environments/${{ inputs.environment }}

      # - name: "Terraform Plan"
      #   run: terraform plan

      # - name: "Terraform Apply"
      #   run: terraform apply -auto-approve
